### ISSUE TITLE
Error Signing in

### ISSUE THREAD

**Issue by axsddlr** [goniszewski/grimoire-web-extension#1]
Steps:

1. enter http://<host_docker_ip>:<port_for_pocketbase_backend>/api
2. enter created account credentials

![Untitled](https://github.com/goniszewski/grimoire-web-extension/assets/1954355/01decc78-77c4-47bc-ad70-49a0a3217fc9)

**Comment by mcanyucel** [comment]
It works on my browser (firefox). Are you sure the credentials are correct?

BTW It should be mentioned somewhere that the api url is the service url with /api suffix ':)
