### ISSUE TITLE
Grimoire API is not reachable

### ISSUE THREAD

**Issue by cikasole** [goniszewski/grimoire-web-extension#9]
Hi,

I've installed grimoire on one host in my home network. It is reachable at <local-IP>:5173, and is working well.
Now I want to use the browser extension. After install it asked for permissions, which went well.
Now I'm stuck with extension's connection to grimoire API. Whatever I try I get the following error: "Grimoire API is not reachable"
I use <local-IP>:5173 for API URL base.
Adding /api path doesn't help. Same with other guesswork paths I tried, the error persists
I couldn't find direct instructions anywhere. Seems it should be self-assuming but I don't get it.

What am I doing wrong?

cikasole

**Comment by goniszewski** [comment]
Hello @cikasole!

The provided URL should point to the app API, so usually it will end with `<GRIMOIRE_HOSTNAME>:5173/api`. So, if this doesn't help, could you open the context menu inside the extension, select the *Network* tab and then tried to sign in? You should be able then to check the request's headers and API's response - it may provide some useful input for us.
<img width="271" alt="image" src="https://github.com/user-attachments/assets/df71453e-df66-4eb8-b22a-a65031b739e6">

**Comment by cikasole** [comment]
Hi,
I connect to grimoire at 192.168.1.100:5173. 
The firefox extension asks me for api url. When I enter 192.168.1.100:5173/api it gives me the error. Please, look at the attached screenshot.
I am little confused with the "extension context" that you mentioned... I don't see any tabs, nor any place where my login credentials are required. Where should I go  for it?

![Screenshot From 2024-10-06 15-52-58](https://github.com/user-attachments/assets/a979351e-2c57-4e2b-94c7-c1560b18a68a)

**Comment by goniszewski** [comment]
Ok, I see. Probably all you need to do is to add the protocol (`http://`) at the very beginning 🙂

Yes, I will need to make it more user friendly.

**Comment by cikasole** [comment]
I tried that already, but it doesn't work either.

I tried to put the URL in browser address field.
http://192.168.1.100:5137/api/ gives an error (see attached image).
http://192.168.1.100:5137/api/health presents me with current server time.
![Screenshot From 2024-10-06 21-17-45](https://github.com/user-attachments/assets/f538df43-d7f4-42f1-aecb-bc5949669047)
![Screenshot From 2024-10-06 21-18-31](https://github.com/user-attachments/assets/8cbae753-ee22-4598-a458-6b39d1607710)

**Comment by cikasole** [comment]
Hi,

I have an update - it works in Chrome! The problem seems to exist only on my Firefox. The version is 115.15.0esr (64-bit).
Both on Linux.

Tomorrow, I'll try Firefox on Windows and Mac... we'll see.

**Comment by goniszewski** [comment]
@cikasole I have found an issue related to Content Security Policy. Basically, Firefox always tried to upgrade HTTP connections to HTTPS, and it obviously failed.

The updated version is now live.
